version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "prowe-recipe-app"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true

[default.build.parameters]
beta_features = true

[default.sync.parameters]
watch = true
beta_features = true
