Transform: AWS::Serverless-2016-10-31

Resources:
  RecipeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userName
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: userName
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend
      Handler: index.graphqlHandler
      Runtime: nodejs20.x
      MemorySize: 512
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowMethods:
            - '*'
          AllowOrigins: 
            - '*'
      Environment:
        Variables:
          RECIPE_TABLE: !Ref RecipeTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RecipeTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - index.ts

Outputs:
  BackendUrl:
    Value: !Sub "${ApiFunctionUrl.FunctionUrl}"